CREATE TABLE %s.stop_times_full (
  stop_id integer NOT NULL,
--  stop_code varchar(45) DEFAULT NULL,
  stop_name varchar(64) DEFAULT NULL,
  stop_desc varchar(128) DEFAULT NULL,
  stop_lat float DEFAULT NULL,
  stop_lon float DEFAULT NULL,
--  stop_geo GEOMETRY DEFAULT NULL,
--  zone_id varchar(45) DEFAULT NULL,
--  stop_url varchar(45) DEFAULT NULL,
  location_type integer DEFAULT NULL,
--  parent_station varchar(45) DEFAULT NULL,
  arrival_time time DEFAULT NULL,
  departure_time time DEFAULT NULL,
  stop_sequence integer DEFAULT NULL,
--  stop_head_sign varchar(8) DEFAULT NULL,
--  pickup_type integer DEFAULT NULL,
--  drop_off_type integer DEFAULT NULL,
--  agency_id integer DEFAULT NULL,
--  route_id integer DEFAULT NULL,
  route_short_name varchar(45) DEFAULT NULL,
--  route_long_name varchar(128) DEFAULT NULL,
--  route_desc varchar(64) DEFAULT NULL,
  route_type integer DEFAULT NULL,
--  route_url varchar(45) DEFAULT NULL,
  route_color char(6) DEFAULT NULL,
  route_text_color char(6) DEFAULT NULL,
  trip_id integer NOT NULL,
  service_id integer DEFAULT NULL,
--  trip_headsign varchar(45) DEFAULT NULL,
  direction_id integer DEFAULT NULL
--  block_id varchar(45) DEFAULT NULL,
--  shape_id varchar(45) DEFAULT NULL
);