CREATE TABLE %s.stop_times_full (
  stop_id integer NOT NULL,
--  stop_code varchar({{length .stops.stop_code}}) DEFAULT NULL,
  stop_name varchar({{length .stops.stop_name}}) DEFAULT NULL,
  stop_desc varchar({{length .stops.stop_desc}}) DEFAULT NULL,
  stop_lat float DEFAULT NULL,
  stop_lon float DEFAULT NULL,
--  stop_geo GEOMETRY DEFAULT NULL,
--  zone_id varchar({{length .stops.zone_id}}) DEFAULT NULL,
--  stop_url varchar({{length .stops.stop_url}}) DEFAULT NULL,
  location_type integer DEFAULT NULL,
--  parent_station varchar({{length .stops.parent_station}}) DEFAULT NULL,
  arrival_time time DEFAULT NULL,
  departure_time time DEFAULT NULL,
  stop_sequence integer DEFAULT NULL,
--  stop_head_sign varchar({{length .stops.stop_head_sign}}) DEFAULT NULL,
--  pickup_type integer DEFAULT NULL,
--  drop_off_type integer DEFAULT NULL,
--  agency_id integer DEFAULT NULL,
--  route_id integer DEFAULT NULL,
  route_short_name varchar({{length .routes.route_short_name}}) DEFAULT NULL,
--  route_long_name varchar({{length .routes.route_long_name}}) DEFAULT NULL,
--  route_desc varchar({{length .routes.route_desc}}) DEFAULT NULL,
  route_type integer DEFAULT NULL,
--  route_url varchar({{length .routes.route_url}}) DEFAULT NULL,
  route_color integer DEFAULT NULL,
  route_text_color integer DEFAULT NULL,
  trip_id integer NOT NULL,
  service_id integer DEFAULT NULL,
--  trip_headsign varchar({{length .trips.trip_headsign}}) DEFAULT NULL,
  direction_id integer DEFAULT NULL
--  block_id varchar({{length .trips.block_id}}) DEFAULT NULL,
--  shape_id varchar({{length .trips.shape_id}}) DEFAULT NULL
);