CREATE TABLE `%s_calendars` (
  `service_id` varchar(45) NOT NULL,
  `monday` tinyint(1) DEFAULT NULL,
  `tuesday` tinyint(1) DEFAULT NULL,
  `wednesday` tinyint(1) DEFAULT NULL,
  `thursday` tinyint(1) DEFAULT NULL,
  `friday` tinyint(1) DEFAULT NULL,
  `saturday` tinyint(1) DEFAULT NULL,
  `sunday` tinyint(1) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`service_id`),
  KEY `start_date_idx` (`start_date`),
  KEY `end_date_idx` (`end_date`),
  KEY `monday_idx` (`monday`),
  KEY `tuesday_idx` (`tuesday`),
  KEY `wednesday_idx` (`wednesday`),
  KEY `thursday_idx` (`thursday`),
  KEY `friday_idx` (`friday`),
  KEY `saturday_idx` (`saturday`),
  KEY `sunday_idx` (`sunday`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
